### ISSUE TITLE
Unitxt site can't be reached

### ISSUE THREAD

**Issue by marukaz** [IBM/unitxt#1017]
There are some URLs of Unitxt website such as https://unitxt.readthedocs.io and https://unitxt.rtfd.io but they are redirected to https://unitxt.ai and it can't be reached.

**Comment by yoavkatz** [comment]
Yes. This a mistake during the transition process to unitxt.ai.  We will fix it as soon as possible.

Yoav

**Comment by yoavkatz** [comment]
This was resolved.

https://unitxt.readthedocs.io/

We will move enable  unitxt.ai in the coming days.

**Comment by marukaz** [comment]
Thank you!
