### ISSUE TITLE
Add warning when metrics scores overwrite each other.

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#1069]
Right now , metrics score overwrite each other (Not referring to the 'score' and 'score_name' , but two metrics can have the same 'f1' score.   

Users find it confusing.  We should at first step make this into a warning.

"Metric 'token_overlap' has the same score as another metric in the metrics list ['token_overlap', 'macro_f1'] .  To avoid overwriting the value , add a score_prefix to the metric (e.g. score_prefix="token_overlap_") .   For more information, see ... "

**Comment by dafnapension** [comment]
Resolved with PR #1124
