### ISSUE TITLE
BUG - dataset loader

### ISSUE THREAD

**Issue by eliyahabba** [IBM/unitxt#1073]
I tried running the following code as described in the tutorial:

`dataset = load_dataset('unitxt/data', 'card=cards.wnli')`
However, I encountered an assertion error:

`AssertionError: Specify either template or template_card_index in card`
Here is the link to the tutorial I followed: [Unitxt Documentation](https://www.unitxt.ai/en/1.7.6/docs/no_installation_usage.html).

Could you please advise on how to resolve this error?

**Comment by elronbandel** [comment]
You need to choose a template. We will either fix the documentation (cc: @michal-jacovi ) or set a default behaviour. Thanks for noting.

**Comment by yoavkatz** [comment]
Hi. I think you are were looking at an old documentation page:

https://www.unitxt.ai/en/1.7.6/docs/no_installation_usage.html

latest documentation is up to date:

https://www.unitxt.ai/en/latest/docs/loading_datasets.html

**Comment by eliyahabba** [comment]
Thanks for pointing that out.
I was probably looking at an old page due to cookies, I'll check the latest documentation.
