### ISSUE TITLE
Repetitive basic instruction in few shot

### ISSUE THREAD

**Issue by eliyahabba** [IBM/unitxt#1075]
I believe there is a bug in the code. When I use few-shot, I expect the basic instruction to appear only once at the beginning, not multiple times. Specifically, this part:
`The following are multiple choice questions (with answers) about science.`
should appear only at the beginning and not before every question. What do you think?

![image](https://github.com/user-attachments/assets/5fa5b303-1322-44fd-a334-9b0df20dd42f)

**Comment by elronbandel** [comment]
This behaviour is intended for that specific template: https://www.unitxt.ai/en/latest/catalog/catalog.templates.qa.multiple_choice.with_topic.fm_eval.html

It did not define an instruction just and input_format. 

This template do work as you expect for example:
https://www.unitxt.ai/en/latest/catalog/catalog.templates.qa.multiple_choice.with_topic.title.html

**Comment by eliyahabba** [comment]
Thanks for the clarification!
