### ISSUE TITLE
same template for different datasets

### ISSUE THREAD

**Issue by borgr** [IBM/unitxt#11]
Can we share a template across datasets? this would require instead of {col1} {col2} have something more generic that can eat any input column (and maybe some meta information of it like its name) for example to have {Sentences} or {Col_name}:{Sentence}.

**Comment by yoavkatz** [comment]
We saw this need also in creme brulee tream.  They want to normalize all datasets of particular type (e.g. entailment to a standard format of "premise","hypothesis","entail"  and summary datasets to "text","summary") and then reuse the same templates accross all datasets.
