### ISSUE TITLE
fixing the typo:   "def text_context_correctness(self):" -> "def test_context_correctness(self):"  blows the test

### ISSUE THREAD

**Issue by dafnapension** [IBM/unitxt#1136]

**Comment by matanor** [comment]
hi @dafnapension , what do you mean by "blows the test"?
is this issue only about fixing the typo?

**Comment by dafnapension** [comment]
ahh... :-) once you change to test_ , the tests go into this method too (which they did not thus far, because of some settings that tells them to look for  test_ ..), and do not manage to complete it successfully, for some error that I do not understand..

**Comment by matanor** [comment]
oh i see.. created a fix ..
thanks for identifying this issue! 

indeed with the test i realize now some change were introduced to the metric names.. (we may need to adjust out user code for that.. )
