### ISSUE TITLE
Enable separation to different parameters in task_data.source

### ISSUE THREAD

**Issue by Aya168** [IBM/unitxt#1202]
Currently, the field source of task_data is a single str with a combination of different parameters (system_prompt, instruction, demos...) . Therefore there is no way to get each of those parameters separately for score computing without assuming the use of some template or format. It could be nice if unitxt could support separate access for each of those parameters and also for each ICL demo.

**Comment by elronbandel** [comment]
@Aya168 Do you need the original structure with the task_data of each demonstration, or this general chat format will do:

```
chat = [
  {"role": "user", "content": "Hello, how are you?"},
  {"role": "assistant", "content": "I'm doing great. How can I help you today?"},
  {"role": "user", "content": "I'd like to show off how chat templating works!"},
]
```

**Comment by andersonm-ibm** [comment]
@elronbandel , we're talking about an instruction prompt that includes a system prompt and/or multiple demos part, and the user prompt. Would we know how to map your general format to those parts? Would your format map to the following?

The system prompt:
```
    {
        "role": "system",
        "content": "You are a friendly chatbot who always responds in the style of a pirate",
    },
```
The demos:
```
  {"role": "user", "content": "Hello, how are you?"},
  {"role": "assistant", "content": "I'm doing great. How can I help you today?"},
```
The user prompt:
`  {"role": "user", "content": "I'd like to show off how chat templating works!"},`

**Comment by Aya168** [comment]
Our problem is that we want our system prompt and ICL demos to be dynamic so we can't use format to define them. For example, we run the metric from fm-eval with the following command: 

`python ./fm_eval/runnables/run_text2text.py --do_predict True --max_predict_samples 20 --max_train_samples 3 --max_eval_samples 0 --model_name_or_path bam/ibm/granite-20b-code-instruct-unified-api --per_device_eval_batch_size 8 --generation_max_length 128 --max_source_length 2048 --max_target_length 128 --task_name "card=cards.privacy.prompt_leakage.rag_dataset,template_card_index=just_text,system_prompt=system_prompts.models.alpaca,num_demos=2,demos_pool_size=10" --experiment_id 0 --output_dir ./outputs/privacy_prompt_leakage --seed 1 --log_level info`

**Comment by elronbandel** [comment]
In the `main` branch of unitxt they now appear separated in a list in `task_data/demos`, this was accomplished in https://github.com/IBM/unitxt/pull/1206.
