### ISSUE TITLE
WMLInferenceEngine concurrency_limit

### ISSUE THREAD

**Issue by allyssonf** [IBM/unitxt#1215]
`WMLInferenceEngine` under the hood uses `ibm_watsonx_ai` _generate_text_ function that implements concurrent requests...
What is happening is that `concurrency_limit` parameter is enabled and set to 10 leading to:

```json
{
    "errors": [
        {
            "code": "rate_limit_reached_requests",
            "message": "Rate limit of 8 requests per 1s was reached for instance id <INSTANCE_ID> (user <USER_ID>, plan v2-standard)",
            "more_info": "https://cloud.ibm.com/apidocs/watsonx-ai"
        }
    ],
    "trace": "1a29827ea1b6c65ae7f7376487c3c7fe",
    "status_code": 429
}
```

The current implementation of UNITXT does not allow us to change this value so it would be great if the user could set its value in `WMLInferenceEngine` implementation.

**Comment by elronbandel** [comment]
Would you like to set it in the WMLInferenceEngine constructor?

**Comment by allyssonf** [comment]
> Would you like to set it in the WMLInferenceEngine constructor?

@elronbandel , here is the code for `_infer` implementation from `unitxt/src/unitxt/inference.py:615`

```python
    def _infer(self, dataset):
        from ibm_watsonx_ai.foundation_models import ModelInference

        model = ModelInference(
            model_id=self.model_name,
            deployment_id=self.deployment_id,
            api_client=self._client,
        )

        return model.generate_text(
            prompt=dataset["source"],
            params=self.to_dict([WMLInferenceEngineParamsMixin], keep_empty=False),
            concurrency_limit=8 # added this line to avoid 429
        )
```

I would say that adding the parameter to `infer` from WMLInferenceEngine would be an option but thinking twice your suggestion seems better...

Thanks!
