### ISSUE TITLE
Additional changes to ArtifactLink and Deprecations

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#1396]
HI Dafna,

Thanks for the work on #1363 . I merged it, and started to look at the new documentations.

1) I see that deprecated artificate are displayed right when they are selected

![image](https://github.com/user-attachments/assets/cd55deb8-97f7-432c-a66e-10ed8b52e67b)

But before we click on them, they are not marked deprecated:

![image](https://github.com/user-attachments/assets/55f64a29-94b8-41ca-9c70-5dace5f74224)

2) In most cases , linked Artifacts are also deprecated, we want to avoid the user needing to write the deprecation message manually.        Yet in some, more rare cases, we want to link artificate but not deprecate.  I wonder how we can achieve both (e.g. add a default  '__deprecated_msg__ ' which is not None to ArtificatLink and replace it with the  "'asset1' is going to be deprecated. In future uses, please access 'asset2' instead.""

**Comment by dafnapension** [comment]
Hi @yoavkatz , thanks for merging. I am puzzled: I could not reproduce the show without the deprecated message. What is the sequence of clicks? Catalog->System Prompts ?     
or otherwise: please send what you see on the address bar, is it:
https://www.unitxt.ai/en/latest/catalog/catalog.system_prompts.__dir__.html  ?

**Comment by yoavkatz** [comment]
That's odd. It does not replicate for me.  Maybe some caching issue?

**Comment by yoavkatz** [comment]
I see your point.  The function is a good idea.      In terms of naming I suggest.

add_link_to_catalog(artifact_linked_to="asset", name="cards.sst2", overwrite=True,deprecate=True)
