### ISSUE TITLE
LoadHF can not load from compressed files

### ISSUE THREAD

**Issue by dafnapension** [IBM/unitxt#286]
dataset https://huggingface.co/datasets/GEM/xlsum is implemented over files compressed as *.tar.bz2.
Currently, these can not be loaded in Streaming mode, as shows in the attached Notebook
[ShowNotImplemented.pdf](https://github.com/IBM/unitxt/files/13296796/ShowNotImplemented.pdf)

I am suggesting a fast patch in a coming pull request.

**Comment by yoavkatz** [comment]
Welcome.

You need to accept the pending invitation and then you can push aPR.

![image](https://github.com/IBM/unitxt/assets/68273864/3b67f15f-b04e-4836-a5d9-bf4e33043153)

Note that you as an external contributor you must commit with sign off.

**Comment by dafnapension** [comment]
suggesting this pull request for a fix of issue 286:
https://github.com/IBM/unitxt/pull/288

**Comment by dafnapension** [comment]
resolved in https://github.com/IBM/unitxt/pull/298
