### ISSUE TITLE
artifact name to include hyphen (minus sign)?

### ISSUE THREAD

**Issue by dafnapension** [IBM/unitxt#294]
Artifacts built for multilingual datasets, are built one per language, and they typically contain the language in their name:
e.g. ` add_to_catalog(card, f"cards.xnli.{lang}", overwrite=True)`
method `verify_legal_catalog_name(name)`  in `/unitxt/src/unitxt/catalog.py` , enforces the names of the artifact to match the reg exp  `r"^[\w" + COLLECTION_SEPARATOR + "]+$"` .
Now, in some datasets, e.g.  `AmazonScience/massive`, the language names do contain hyphen, e.g: ` 'de-DE', 'el-GR', 'en-US'` .
Should the regular expression be expanded to also allow hyphens?  Or is there a reason not to?
Might a twicked artifact name, e.g.  `cards.amazon_mass.en_US`   (for language `en-US`), cause a problem downstream? Are there tools that depend on the name of the language being part of the name of the artifact?

**Comment by yoavkatz** [comment]
Let's wait for @elronbandel's input.  Maybe it is required due to python to json naming conversion.
