### ISSUE TITLE
Add a ability to map specific values in List

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#326]
Currently MapInstanceValues - maps complete valus in fields

MapInstanceValues(mappers={"labels": {"[]": ["none"]}}, strict=False),

However, in multi label classification, we would like to map individual elements within a field.

We would like an option 'process_every_value' to be added to MapInstanceValues to allow working on list.

MapInstanceValues(mappers={"labels": {"a": "apple", "b": "bandana"}}, strict=False, process_every_value=True),

**Comment by dafnapension** [comment]
Hi @yoavkatz , please see [pull request](https://github.com/IBM/unitxt/pull/331) that addresses this issue.
