### ISSUE TITLE
Add new Augmentor to add random suffix to text

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#342]
Augmentors  (See #250 ) allow random modification of the input text of the models, to test model robustness.

Today, there is only a single kind of Augmentor: [AugmentWhitespace](https://github.com/IBM/unitxt/blob/77e6e3d37521330a62300d27c6cf08e22adac090/src/unitxt/operators.py#L359):

which is registered in:

https://github.com/IBM/unitxt/blob/main/prepare/augmentors/augment_whitespace.py

Note that augmentors have two configurations, augment the entire input provided to the model (which includes the instructions, template prompt, etc). or only specific defined fields in the task.  This is controlled by the 

operator = AugmentWhitespace(augment_model_input=True)
vs
operator = AugmentWhitespace(augment_task_input=True)

The current whitespace augments replaces any existing whitespace in the string with random 1-3 whitespace chars.
```
class AugmentWhitespace(Augmentor):
    """
    Augments the inputs by replace existing whitespace with other whitespace.
    Currently each whitespace is replaced by a random choice of 1-3 whitespace charaters (spcae, tab, newline).
    """

    def process_value(self, value: Any) -> Any:
        import re

        words = re.split("(\s+)", value)
        new_value = ""

        for word in words:
            if word.isspace():
                new_value += random.choice(["\n", "\t", " "]) * random.randint(1, 3)
            else:
                new_value += word
        return new_value
```
        
There is a request to support augmentation of whitespace, but only at the end (even if there was no whitespace at the end).

One option is to add a new Augmentor class that randomly add one of a set of suffixes.

class AugmentSuffix(Augmentor)

That has a list of possible suffixes that the user can customize and will be randomly added.  

operator = AugmentSuffix(augment_model_input=True, suffixes=[" ", "\n", ""])

We can add the option for weighted selection by passing a dictionary.

operator = AugmentSuffix(augment_model_input=True, suffixes={" ": 2 , "\n": 3 ,"" : 5})

**Comment by dafnapension** [comment]
Hi @yoavkatz ,  please see [pull request](https://github.com/IBM/unitxt/pull/347)
