### ISSUE TITLE
RenderFormatTemplate is not a template

### ISSUE THREAD

**Issue by jlquinn** [IBM/unitxt#351]
In templates.py there is RenderFormatTemplate, RenderAutoFormatTemplate, and RenderTemplatedICL.  In theory I expected these to be templates, but they derive from ABC, not Template.

**Comment by jlquinn** [comment]
For instance, trying to add RenderFormatTemplate to a TemplateList in a dataset card gives an error.

**Comment by yoavkatz** [comment]
Not relevant after refactor.
