### ISSUE TITLE
Potential error in metrics/F1MultiLabel

### ISSUE THREAD

**Issue by sam-data-guy-iam** [IBM/unitxt#373]
@matanor @elronbandel  In F1MultiLabel, I think the following line is a mistake
````
labels = [
    lbl
    for lbl in {label for reference in references for label in reference}
    if lbl not in self.classes_to_ignore
]
````
This is supposed to be collecting the unique non-ignored label values in reference.  But since reference is a list of strings due to the line references = [reference[0] for reference in references], this ends up generating a list of the single characters in the list, which creates labels that didn't exist.  For instance, with the inputs 
````
references = [["A B"], ["BC D"], ["C"], ["123"]]
predictions = [["B", "AB", "A"], ["A", "bC", "BC DF"], ["c", " C"], [13, 23, 234]]
````
for the first pair of input and prediction, the result of labels is [' ', 'A', 'B'] (the individual characters of 'A B'), not just 'A B'.  That is, ' ', 'A', and 'B' are new label classes that are invented.  I think that one of the following is the case:
1) either it should instead be labels = set([reference for reference in references if reference not in self.classes_to_ignore]), or use set difference
2) Possibly F1MultiLabel was intended to allow multiple reference values per prediction, rather than the reverse.  Possibly the assertion was copied from F1 without changing it to check if there is only one prediction per reference.

Also, it would be useful to have examples in prepare/metrics/f1.py illustrating use of these metrics, as the other ones have.

**Comment by yoavkatz** [comment]
F1MultiLabel expects to receive for each samples.
prediction - a list strings (predicted labels)
references - a list of lists of string (labels) 


![image](https://github.com/IBM/unitxt/assets/68273864/6e1c2cd6-e2f9-4db6-a951-7407fb4c6f31)

I agree we need to update the documentation.

You can see examples in the test (unitxt/tests/test_metrics.py) 

So in your example , the expected format for the references is:

[ 
[["A B"]], 
[["BC D"]], 
[["C"]],
[["123"]],
]

You should have gotten an error message. but there was a bug in the test:
    for reference in references:
            assert isinstance(
                references, list.   <--- should be reference
            ), f"Each reference is expected to list of strings in F1 multi label metric. Received reference: {reference}"

**Comment by yoavkatz** [comment]
Fix to error message is here:

https://github.com/IBM/unitxt/pull/390
