### ISSUE TITLE
In GlobalMetric confidence interval, need check to make sure new generated value is not NaN

### ISSUE THREAD

**Issue by sam-data-guy-iam** [IBM/unitxt#389]
@matanor @elronbandel 
In GlobalMetric's compute_global_confidence_intervals, the following lines of code generate new draws to replace any with NaN values.  But there is no check that the resulting samples do not also result in NaNs (as happened to me).  One can debate whether you would want to leave it as is if there are NaNs (i.e. the user may want to know how likely NaNs are, if these are valid values).   I think a better solution is to set some maximum number of tries, say 50, and try one by one to replace the NaNs with a new draw (up to the number of tries), replacing it if not NaN, otherwise continuing, until either the number of tries is reached or there are no NaNs left.  And then finally removing any NaNs (by recalculating error_indices on the final scores vector).   The code as it exists simply tries again without any check on the replacement validity.
On a related note, does a similar type of check need to be done on the score_based_confidence intervals if not global?
````
if n_errors > 0:
           new_scores = random_gen.choice(scores, n_errors, replace=True)
           scores = scores[~error_indices]
           scores = np.concatenate([scores, new_scores])
````

**Comment by sam-data-guy-iam** [comment]
@matanor I think what needs to be done instead is simply when resampling new_scores to sample from scores[~error_indices] so that none will be NaN.  I apologize I was thinking it was generating new resamplings from the original references and predictions, like scores[error_indices] = random_gen.choice(scores[~error_indices], n_errors, replace=True)

**Comment by matanor** [comment]
@sam-data-guy-iam IIUC your suggestion is to draw non-NaN values, since there is no point in resampling values that may be NaN, if we are to remove NaN values in the first place.. This sounds like a good idea to me ...
Do you have the capacity to do this fix?

**Comment by sam-data-guy-iam** [comment]
I made the change for global metrics already in my PR for the InstanceMetric.  I used the same method as in InstanceMetric to simply resample only from the non NaN scores, so we can close this issue once the PR is integrated.

**Comment by matanor** [comment]
nice! tks for fixing this..
