### ISSUE TITLE
Importing dependencies which are not part of unitxt dependencies

### ISSUE THREAD

**Issue by jezekra1** [IBM/unitxt#596]
Some metrics import `transformers` library, which is not part of the dependencies. Please consider using some import guard such as:

```python
try:
  import transformers
except ImportError as e:
  raise ImportError("please install the transformers library using pip install 'unitxt[transformers]'").
```

Consider switching to poetry which implements best practices of managing dependencies in pyproject.toml instead of custom logic in `setup.py`.
See:
[PEP-0631](https://peps.python.org/pep-0631/)
[Poetry](https://python-poetry.org/)
[extras](https://python-poetry.org/docs/pyproject/#extras) such as `pip install unitxt[transformers]`  

Source of the issue:

https://github.com/IBM/unitxt/blob/203f55c5e8eddcfe97e23b40847cfed08e08c8eb/src/unitxt/metrics.py#L1766

`transformers` is part of the [test.rqr](https://github.com/IBM/unitxt/blob/main/requirements/tests.rqr) group however there is no mention of this in the documentation and also probably was not meant for the end users, rather for tests.

**Comment by elronbandel** [comment]
We have a mechanism for handeling the requirements needed for differen operators.
In your example it defined here: https://github.com/IBM/unitxt/blob/203f55c5e8eddcfe97e23b40847cfed08e08c8eb/src/unitxt/metrics.py#L1744C5-L1744C53
Did it not work in your case @jezekra1 ?

**Comment by jezekra1** [comment]
Not in this case `torch` is not mentioned in the list and also maybe we're not invoking the pipeline the intended way?

Snippet from the error:
```
ModuleNotFoundError                       Traceback (most recent call last)

File ~.../unitxt/metrics.py:1374, in Perplexity.AbstractLM.__init__(self, model_name)
   1373 def __init__(self, model_name):
-> 1374     import torch
   1375     from transformers import AutoTokenizer
   1377     self.model_name = model_name

ModuleNotFoundError: No module named 'torch'
```
We're using `evaluate` function from `eval_utils` (older version):
https://github.com/IBM/unitxt/blob/e0f3fc72bcae095533410a7b22f124ac7d4532e7/src/unitxt/eval_utils.py#L9
