### ISSUE TITLE
MultipleSourceLoader - ability to load a from multiple sources

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#701]
There is a need to load data from multiple source  (e.g. train set from HF and test set for CSV)

MultipleSourceLoader(loaders =  LoadHF(LoadHF(path="public/data",split="train",  LoadCSV({"test": "mytest.csv"})) ]

The code need to be added to loaders.py.

I think something along these lines.
```
class MultipleSourceLoader(Loader):
    loaders: List[Loaders] 

    def process(self):
           multi_stream = MultiStream()
           for loader in loaders:
                  loader_multistream = loader.process()
                  for (split, stream) in loader_multistream().items()
                        if (split in multi_stream) 
                              raise ValueError(f"Multiple sources specify '{split}' split")
                        multi_stream[split] = stream
          return multi_stream
  ```        
Need to add two tests in test_loaders.py.

1. Successful merge
2. Conflicting stream names.

**Comment by yoavkatz** [comment]
@elron - please let me know if you agree this is the right direction.

**Comment by elron** [comment]
I'm sorry, how is this related to me? (Did you try to mention someone else and mentioned me by mistake?)

**Comment by yoavkatz** [comment]
Sorry @elron . Meant to another @elronbandel .   

In any case issue was completed in PR #707
