### ISSUE TITLE
Ability to parse all valid type aliases

### ISSUE THREAD

**Issue by pawelknes** [IBM/unitxt#715]
Currently function `parse_type_string` (in `src/unitxt/test_utils.py`) fails when a user passes built-in non-capitalised type aliases, for example: `list` instead of `List`, which is valid since Python 3.9. 
The same happens when using a "bitwise or operator" for union types, for example: `int | str` instead of `Union[int, str]`. 
The function also fails when a type string contains full module name for example: `typing.Dict`.

Suggestion: expanding the functionality so that `parse_type_string` can process all valid type aliases

**Comment by pawelknes** [comment]
@elronbandel what do you think about this idea?

**Comment by elronbandel** [comment]
@pawelknes it could be fixed easily but if i. understand correctly it wont work with python 3.8 no?

**Comment by pawelknes** [comment]
> @pawelknes it could be fixed easily but if i. understand correctly it wont work with python 3.8 no?



Since `parse_type_string` accepts strings I was thinking about adding a step which will firstly preprocess string so that it's compatible with `typing` no matter if version is before or after Python 3.9, maybe like this snippet (just an initial idea):

```
def format_type_string(type_string: str) -> str:
    types_map = {"list": "List", "dict": "Dict", "tuple": "Tuple", "typing.": ""}
    for k, v in types_map.items():
        type_string = type_string.replace(k, v)
    return type_string
```

And it could also deal with `|` into `Union`. I can make a PR if you accept the idea (or am I missing something?)

**Comment by elronbandel** [comment]
You are right. Sounds cool and should work!

**Comment by pawelknes** [comment]
https://github.com/IBM/unitxt/pull/772
