### ISSUE TITLE
Add to all base operator eager mode

### ISSUE THREAD

**Issue by elronbandel** [IBM/unitxt#841]
If all the base operators had eager mode it would be easier to debug.
This addition can be simple: adding to every operator an option to run on all the stream it got as list, and create list of its own with the ready instance and pass them on to the next operator as list.

**Comment by dafnapension** [comment]
@elronbandel , that is a neat idea!
Perhaps can be implemented by just changing the recipes:
add a 'filler' in between two adjacent operators on the recipe. The filler will consume a whole stream from its predecessor, and only when completing to consume - will hand over a whole list of instances to its successor. 
Is this acceptable?
