### ISSUE TITLE
Unitxt explores fails on generation tasks that require additional dependencies

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#885]
<img width="951" alt="image" src="https://github.com/IBM/unitxt/assets/68273864/56af55eb-ba44-464c-b5c7-04c9acae7fcf">

We need to at least install the basic test requirements.

**Comment by duckling69** [comment]
can i work on this // @yoavkatz @eladven

**Comment by elronbandel** [comment]
Its solved on the huggingface side, for now on all our huggingface assets will install the up to date tests requirement so everything works
