### ISSUE TITLE
Add optional default values to task fields

### ISSUE THREAD

**Issue by yoavkatz** [IBM/unitxt#893]
For some task fields, like "text_type", It would good to have defaults so the user does not have to specify them in the card.  For example for text_type it could be "text".

I suggest adding another field to Task , called " defaults" of type Dict[str, Any].

It would add the default values for any instance that does not already have the field.

**Comment by yoavkatz** [comment]
@pawelknes . If you are want to take this issue, it would be great. It continues the work on Tasks.

**Comment by elronbandel** [comment]
My only concern about it is that mechanism does not support inheritance. 

For example if we want to create task for sentiment analysis ideally we would like to inherit most of the definition from the classification task and just set the `class_type=sentiment` as default. Yet our only way to do it and save it in the catalog is to duplicate the original task. Not to mention we dont have  a native way to specify the templates for classification are compatible with sentiment analysis (and ofcourse more can be added specfically just for this task)

If lets say we had a task of type `SubTask` it could inherit regular task and add defaults.
Then sentiment analysis could be define as `SubTask(task="task.classification.multi_class", defaults={"type_of_class":sentiment})`
Or ofcourse it can support: `SubTask(task=Task(...),  defaults={"type_of_class":sentiment})` and be compatible with your original suggestion. 

Another advantage of sub tasks is that it can yield an instruct lab like taxonomy tree where you have sub tasks like:  `SubTask(task="tasks.generation", defaults={"input_type":"email"})` and then `SubTask(task="tasks.generation.from_email", defaults={"output_type":"summary"}) `and  `SubTask(task="tasks.generation.from_email", defaults={"output_type":"bullet points"})`

**Comment by yoavkatz** [comment]
Hi. I agree that SubTask is a useful extension.  Actually we have this syntax:

tasks.generation[defaults={"input_type":"email"}]

The difference is that you want to defaults to be added and not replaced, but this is allow true for metrics

tasks.generation[metrics=["metrics.my_metric"]]

we may want to add the metric and not replace all the existing metrics.

**Comment by pawelknes** [comment]
> @pawelknes . If you are want to take this issue, it would be great. It continues the work on Tasks.

Sure, I can work on this
