### ISSUE TITLE
Why do we verify after preparing and not before

### ISSUE THREAD

**Issue by borgr** [IBM/unitxt#94]
in Stream we first make actions (in prepare()) and only then verify() the inputs.
So we both waste time and can't assume everything makes sense in the prepare.
If this is fixed, fix FieldOperator prepare() that starts with an assert section as well

**Comment by elronbandel** [comment]
The reason is that verification is meant to make sure your inputs are correct. than you can do with it whatever you want and trust your actions while preparing.
