### ISSUE TITLE
Turn safety and regard metrics to pure unitxt

### ISSUE THREAD

**Issue by elronbandel** [IBM/unitxt#946]
Those metrics cannot be loaded trough huggingface load dataset until re implementated  as unitxt metrics.

**Comment by dafnapension** [comment]
Hi @elronbandel , I gladly accept, but need some education..

**Comment by dafnapension** [comment]
Running prepare/cards/bold.py  which uses: ` metrics=["metrics.regard"]`, am I expected to go through `metrics.regard._compute(..)` ?  It seems that I do not.  I am missing the point here, I suspect.

**Comment by dafnapension** [comment]
Resolved by PR #1004
